{% set name = "prometheus_flask_exporter" %}
{% set version = "0.21.0" %}
{% set sha256 = "ebbc016c1e3d16e7cd39fe651a6c52ac68779858b2d5d1be6ddbc9e66f7fc29f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  skip: true  # [py<36]

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - flask
    - prometheus_client

test:
  imports:
    - prometheus_flask_exporter
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/rycus86/prometheus_flask_exporter
  summary: Prometheus metrics exporter for Flask
  description: |
    This library provides HTTP request metrics to export into Prometheus.
    It can also track method invocations using convenient functions.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  license_url: https://github.com/rycus86/prometheus_flask_exporter/blob/master/LICENSE
  dev_url: https://github.com/rycus86/prometheus_flask_exporter
  doc_url: https://github.com/rycus86/prometheus_flask_exporter/blob/master/README.md
  doc_source_url: https://github.com/rycus86/prometheus_flask_exporter/blob/master/README.md

extra:
  recipe-maintainers:
    - xhochy
