{% set name = "prometheus_flask_exporter" %}
{% set version = "0.22.4" %}
{% set sha256 = "959b69f1e740b6736ea53fe5f28dc2ab6229b2ebeade6582b3dbb5d74c7d58e4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<36]

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - flask
    - prometheus_client

test:
  imports:
    - prometheus_flask_exporter
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/rycus86/prometheus_flask_exporter
  summary: Prometheus metrics exporter for Flask
  description: |
    This library provides HTTP request metrics to export into Prometheus.
    It can also track method invocations using convenient functions.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/rycus86/prometheus_flask_exporter
  doc_url: https://github.com/rycus86/prometheus_flask_exporter/blob/master/README.md

extra:
  recipe-maintainers:
    - xhochy
