{% set name = "prometheus_flask_exporter" %}
{% set version = "0.18.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 01c8282eb695596531f29f4869c1b127e1918af4f191f1215c4b0b0d081f757e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - flask
    - prometheus_client

test:
  imports:
    - prometheus_flask_exporter
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/rycus86/prometheus_flask_exporter
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Prometheus metrics exporter for Flask

extra:
  recipe-maintainers:
    - xhochy
