{% set name = "prometheus_flask_exporter" %}
{% set version = "0.20.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 480ad73730e06ac6f6f45913595a588ce84811b6aaf11ff9532e530512e9d13d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - flask
    - prometheus_client

test:
  imports:
    - prometheus_flask_exporter
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/rycus86/prometheus_flask_exporter
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Prometheus metrics exporter for Flask

extra:
  recipe-maintainers:
    - xhochy
